name: Build EXE Scanner

on:
  workflow_dispatch: # لتشغيله يدوياً بضغطة زر

jobs:
  build-windows-exe:
    runs-on: windows-latest # تشغيل خادم ويندوز لإنشاء الـ EXE
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install Tools
        run: |
          pip install requests pyinstaller
          
      - name: Compile Script to EXE
        run: |
          pyinstaller --onefile local_scanner.py
          
      - name: Upload EXE Binary
        uses: actions/upload-artifact@v4
        with:
          name: V2Ray-Egypt-Scanner
          path: dist/local_scanner.exe
